### PR TITLE
Fix unescaped dashes

### PR DESCRIPTION
**Pull request by ashpool37**
I made a change that worked for me. Your last adjustment apparently was an attempt to replace more underscores, while the problem I was having was related to dashes ("-").

### CODE REVIEW

**Comment by GokulDas027** [comment]
Dashes aren't supposed to cause such markdown parsing errors at first place..
I have a repo with dashes in it's name, and has been working fine!!

**Comment by ashpool37** [comment]
This is the specific repo I'm having a problem with.
https://github.com/Hackathon-on-Internet-freedom/ShadoWG 

Notice there are three dashes in organization name. Maybe you could test your latest version out with a similar organization name and see if it would work. Again, the exact error message I'm getting
`unable to send message: Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'`
specifically mentions dashes. I don't know if this is related to Markdown.

**Comment by ashpool37** [comment]
Closing this for now, as I may push more changes to my fork's master which can deviate its feature set from the one intended by the original project.

**Comment by GokulDas027** [comment]
Hi bro, 
I just found the test failed for this pushes, which of course is just the TelegramBridge itself.. and was curious why it happens.. do you have any idea?
It didn't happened for the other PR!

**Comment by ashpool37** [comment]
> I just found the test failed for this pushes

Hmm... Says `unable to send message: Not Found`. I don't know where that might come from, I literally just added some ReplaceAll calls on `event`, `repo`, and `actor` strings. As far as I understand, those values go into the message body and therefore shouldn't affect message deliverability, provided they can be parsed. It sure wouldn't hurt for the error messages to be a little more verbose!

**Pull request merged**
